apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-ghost
  labels:
    app: ghost
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/ghost